[package]
name = "weathermanrs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
dotenv = "0.15.0"
ratatui = "0.28.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
